# Generated by Django 4.2.25 on 2025-10-02 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('image_key', models.CharField(blank=True, max_length=255, null=True)),
                ('thermal_conductivity', models.FloatField()),
                ('price_per_m2', models.DecimalField(decimal_places=2, max_digits=10)),
                ('density', models.FloatField()),
                ('fire_rating', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('DELETED', 'Удалён'), ('FORMED', 'Сформирован'), ('COMPLETED', 'Завершён'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=20)),
                ('creation_datetime', models.DateTimeField(auto_now_add=True)),
                ('formation_datetime', models.DateTimeField(blank=True, null=True)),
                ('completion_datetime', models.DateTimeField(blank=True, null=True)),
                ('climate_zone', models.CharField(max_length=100)),
                ('required_r_value', models.FloatField()),
                ('wall_type', models.CharField(max_length=50)),
                ('norm_standard', models.CharField(max_length=50)),
                ('total_thickness', models.FloatField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_requests', to=settings.AUTH_USER_MODEL)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RequestInsulator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.IntegerField()),
                ('is_main', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('calculated_thickness', models.FloatField(blank=True, null=True)),
                ('insulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.insulator')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.request')),
            ],
            options={
                'unique_together': {('request', 'insulator')},
            },
        ),
    ]
