# Generated by Django 4.2.25 on 2025-10-02 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insulator',
            old_name='name',
            new_name='insulator_name',
        ),
    ]
