# Generated by Django 4.2.25 on 2025-10-02 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_rename_name_insulator_insulator_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insulator',
            old_name='description',
            new_name='insulator_description',
        ),
    ]
