# Generated by Django 4.2.25 on 2025-10-02 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0003_rename_description_insulator_insulator_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='status',
            new_name='status_request',
        ),
    ]
