# Generated by Django 4.2.25 on 2025-10-02 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0004_rename_status_request_status_request'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestinsulator',
            old_name='comment',
            new_name='user_comment',
        ),
    ]
