# Generated by Django 4.2.25 on 2025-10-02 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0005_rename_comment_requestinsulator_user_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestinsulator',
            old_name='user_comment',
            new_name='comment',
        ),
    ]
