# Generated by Django 4.2.25 on 2025-10-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0006_rename_user_comment_requestinsulator_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insulator',
            old_name='insulator_description',
            new_name='description',
        ),
    ]
