# Generated by Django 4.2.25 on 2025-10-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0007_rename_insulator_description_insulator_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insulator',
            old_name='description',
            new_name='insulator_description',
        ),
    ]
