# Generated by Django 4.2.25 on 2025-10-02 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0008_rename_description_insulator_insulator_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestinsulator',
            old_name='comment',
            new_name='user_comment',
        ),
    ]
