# Generated by Django 4.2.25 on 2025-10-05 07:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0009_rename_comment_requestinsulator_user_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='InsulatorRequest',
        ),
    ]
