# Generated by Django 4.2.25 on 2025-10-05 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0010_rename_request_insulatorrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestInsulator',
            new_name='DetailRequestInsulator',
        ),
    ]
