# Generated by Django 4.2.25 on 2025-10-05 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0011_rename_requestinsulator_detailrequestinsulator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailrequestinsulator',
            old_name='request',
            new_name='detail_request',
        ),
        migrations.AlterUniqueTogether(
            name='detailrequestinsulator',
            unique_together={('detail_request', 'insulator')},
        ),
    ]
