# Generated by Django 4.2.25 on 2025-10-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0012_rename_request_detailrequestinsulator_detail_request_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailrequestinsulator',
            old_name='is_main',
            new_name='DetailRequestActive',
        ),
        migrations.RenameField(
            model_name='insulator',
            old_name='is_active',
            new_name='Insulator_active',
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='climate_zone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='norm_standard',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='required_r_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='wall_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
