# Generated by Django 4.2.25 on 2025-10-20 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('calculator', '0013_rename_is_main_detailrequestinsulator_detailrequestactive_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='detailrequestinsulator',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='DetailRequestActive',
            field=models.BooleanField(default=False, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='calculated_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Рассчитанная толщина'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='detail_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='calculator.insulatorrequest', verbose_name='Заявка'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='insulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.insulator', verbose_name='Изолятор'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='order',
            field=models.PositiveIntegerField(verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='user_comment',
            field=models.TextField(blank=True, default='', verbose_name='Комментарий пользователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insulator',
            name='Insulator_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='density',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Плотность'),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='fire_rating',
            field=models.CharField(max_length=50, verbose_name='Класс пожаробезопасности'),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='image_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ключ изображения'),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='insulator_description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='insulator_name',
            field=models.CharField(max_length=200, verbose_name='Название изолятора'),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за м²'),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='thermal_conductivity',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Теплопроводность'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='climate_zone',
            field=models.CharField(max_length=100, verbose_name='Климатическая зона'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='formation_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='norm_standard',
            field=models.CharField(max_length=100, verbose_name='Нормативный стандарт'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='required_r_value',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Требуемое R-значение'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='status_request',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('FORMED', 'Сформирована'), ('COMPLETED', 'Завершена'), ('REJECTED', 'Отклонена'), ('DELETED', 'Удалена')], default='DRAFT', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='total_thickness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Общая толщина'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='wall_type',
            field=models.CharField(max_length=100, verbose_name='Тип стены'),
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone number')),
                ('nickname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nickname')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Is manager?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Is admin?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insulator_requests', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_requests', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер'),
        ),
    ]
