# Generated by Django 4.2.25 on 2025-10-20 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('calculator', '0014_alter_detailrequestinsulator_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='DetailRequestActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='calculated_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='detail_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.insulatorrequest'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='insulator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculator.insulator'),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='detailrequestinsulator',
            name='user_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='Insulator_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='density',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='fire_rating',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='image_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='insulator_description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='insulator_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='price_per_m2',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='insulator',
            name='thermal_conductivity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='climate_zone',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='completion_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='creation_datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='formation_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='managed_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='norm_standard',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='required_r_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='status_request',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('DELETED', 'Удалён'), ('FORMED', 'Сформирован'), ('COMPLETED', 'Завершён'), ('REJECTED', 'Отклонён')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='total_thickness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='insulatorrequest',
            name='wall_type',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='detailrequestinsulator',
            unique_together={('detail_request', 'insulator')},
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
